### ISSUE TITLE
Is search.aufe.cf and search.ecnu.cf be walled?

### ISSUE THREAD

**Issue by Zhenghao-Wen** [librarycloud/list#7]
They show the error message
"**502 Bad Gate way**"
just like the website search.aust.cf 
(The search.aust.cf had already been walled.)
Is that's true?

**Comment by iefnuy** [comment]
search.aufe has been fixed.
search.ecnu  service has exhausted its traffic. Wait for reset on the 1st of next month.

**Comment by Zhenghao-Wen** [comment]
thanks for repair.
